apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: demoapp
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: 
        - spot
        - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        - arm64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - t4g.small
        - t4.small
        - t3.medium
        - t2.medium
        - t4g.medium
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - ap-south-1a
        - ap-south-1b

  limits:
    resources:
      cpu: 4000
  ttlSecondsAfterEmpty: 15
  #consolidation:
  #  enabled: true
  
  kubeletConfiguration:
    maxPods: 20
  
  providerRef:
    name: demoapp-node-template
  

  
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: demoapp-node-template
spec:
  subnetSelector:
    karpenter.sh/discovery: awsome-cluster
  securityGroupSelector:
    karpenter.sh/nodesg: awsome-cluster
  userData:  |
    # run any shell scripts 
    # change configuration

  #amiSelector:
  #  ids: "ami-0c4ddcdf9b8aa7e0f,ami-032fa19df501b20ce"
  tags:
    Name: karpenter-awsome-node
    App: foo-bar-app
    ManagedBy: karpenter